name: Build Floyd Cli
on:
    push:
        branches:
          - main

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build
        run: |
          make PLATFORM=linux CC=gcc build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: example linux
          path: ${{ github.workspace }}/build/linux/example

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build
        run: |
          make PLATFORM=macos CC=clang build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: example macos
          path: ${{ github.workspace }}/build/macos/example

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: make package_windows
      run: |
        mingw32-make PLATFORM=windows CC=gcc build
      shell: cmd
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
         name: example windows
         path: ${{ github.workspace }}/build/windows/example
